title: Yann Pequignot
url: "yannpequignot.github.io"
#baseurl: "/"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: no


sass:
    style: compressed
    sass_dir: _sass

nav:
#  - name: "About"
#    link: "index"
 - name: "Publications"
   link: "publis"
 - name: "Talks"
   link: "talks"
 - name: "Teaching"
   link: "Teach"
 - name: "Contact"
   link: "contact"


plugins:
  - jekyll-remote-theme

remote_theme:
  - remote_theme: ankitsultana/researcher@gem